name: whattowatch
description: random movie and tv show generatror

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  flutter_colorpicker: ^1.0.3
  flutter_custom_clippers: ^2.0.0
  flutter_fadein: ^2.0.0
  get: ^4.6.1
  google_fonts: ^2.3.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  photo_view: ^0.13.0
  share_plus: ^3.1.0
  smooth_star_rating: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: null
  flutter_native_splash: null
  dapackages: null

dependency_overrides:
  platform: ^3.1.0


flutter:
  uses-material-design: true

# Run >>> flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "Logo.png"

# Run >>> flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#6C5CD5"
  image: Splash.png
  color_dark: "#303030"
  image_dark: Splash.png
  android: true
  ios: true
  web: true
  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center
  #fullscreen: true
