name: code
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  cached_network_image: ^3.0.0
  carousel_slider: ^3.0.0
  flutter_colorpicker: ^0.4.0
  flutter_custom_clippers: ^1.1.2
  flutter_fadein: ^2.0.0
  get: ^3.26.0
  google_fonts: ^2.0.0
  hive: ^2.0.1
  hive_flutter: ^1.0.0
  path_provider: ^2.0.1
  photo_view: ^0.11.1
  share_plus: ^2.0.0
  smooth_star_rating: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: null
  flutter_native_splash: null

flutter:
  uses-material-design: true

# Run >>> flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "Logo.png"

# Run >>> flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#6C5CD5"
  image: splash.png
  color_dark: "#303030"
  image_dark: Splash.png
  android: true
  ios: true
  web: true
  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center
  #fullscreen: true
